name: Release asynciolimiter

on:
  release:
    types: [published]

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Verify version
        run: |
          PY_VER=$(python -c "import asynciolimiter;print(asynciolimiter.__version__)")
          echo Python version - "$PY_VER"
          SETUP_VER=$(awk "/version =/ { print \$3 }" setup.cfg)
          echo Setup.cfg version - "$SETUP_VER"
          [[ $PY_VER == $SETUP_VER ]]
          TAG_VER=$(echo ${{ github.event.release.tag_name }} | cut -c 2-)
          echo Tag version "$TAG_VER"
          [[ $TAG_VER == $PY_VER ]]
  upload_test_pypi:
    needs: check_version
    runs-on: ubuntu-latest
    environment: Test PyPi
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build wheel
        run: pip wheel .
      - name: Install twine
        run: pip install twine
      - name: Publish on Test PyPi
        run: twine upload -r testpypi -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} asynciolimiter-*.whl
      - uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: asynciolimiter-*.whl
  upload_production_pypi:
    needs: upload_test_pypi
    runs-on: ubuntu-latest
    environment: Production PyPi
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/download-artifact@v4
        with:
          name: wheel
      - name: Install twine
        run: pip install twine
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'asynciolimiter-*.whl'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish on Production PyPi
        run: twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} asynciolimiter-*.whl

